<?php
	$nav = '';
	$page = '';
	include_once('parts/header.php');
?>


<header class="page-header">
	<h1 class="page-title">Affiliate Program</h1>
	<p class="page-subtitle">Earn 20% on every sale you generate. Plus earn 10% every sale generated by affiliates you refer!</p>
</header>


<section class="affiliates">

	<p class="intro">It's really easy. Simply sign up for the program and use the provided tracking links to promote WP Migrate DB Pro on your site, blog, Facebook, Twitter, or other social networks.</p>

	<p>
		<a href="#" class="btn btn--lg btn--danger">Join Our Affiliate Program</a>
		<span>Already have an account? <a href="#">Login here</a></span>
	</p>

	<hr>

	<h2>Frequently Asked Questions</h2>

	<p class="faq__question">Do you provide a coupon code to promote?</p>
	<p class="faq__answer">Yep. Sign in to your account and you'll see a coupon code in the offer details.</p>

	<p class="faq__question">Where can I find my link to refer other affiliates?</p>
	<p class="faq__answer">You'll find your link in your account under Reports > Referral Report. You earn 10% of every sale generated by every affiliate you refer!</p>

	<p class="faq__question">When do payouts occur?</p>
	<p class="faq__answer">Between the 1st and 10th of every month.</p>

	<p class="faq__question">Is there a minimum payout?</p>
	<p class="faq__answer">Yes. Your account balance must be at least $50 to receive a payout.</p>

	<p class="faq__question">Can I earn commissions on my own purchases?</p>
	<p class="faq__answer">No. This is considered fraud and is against our Affiliate Program Terms &amp; Conditions.</p>

	<p class="faq__question">What affiliate software do you use?</p>
	<p class="faq__answer">HasOffers</p>


	<hr>

	<p class="intro spacer">
		<span>Have another questions? Send ‘em our way </span>
		<a href="#" class="btn btn--outline btn--primary">Send Email</a>
	</p>

</section>


<?php include_once('parts/testimonials.php'); ?>


<?php include_once('parts/footer.php'); ?>